name: Generate and run contract tests
on:
  workflow_dispatch:



jobs:

  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: "starting Postman tests on ${{github.ref_name}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: generate and run tests using Postman's Newman
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMANKEY }}
          collection: tests/postman_collection.json
          environment: tests/postman_environment.json
          envVar: '[{ "key": "env-TESTMOR_CREDENTIALS", "value": ${{ secrets.TESTMOR_CREDENTIALS }} }]'
      #collection and env sourced from https://github.com/allenheltondev/postman-contract-test-generator
      #a Postman meta-collection that uses postman scripts to generate tests on-the-fly from an OAS file

      - name: Notify slack success
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':white_check_mark: successfully completed Postman tests on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify slack failure
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':red_circle: failed Postman tests on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

