name: bundle OAS

on:
  workflow_dispatch: #manual trigger or ...
  push: #when changes are pushed to default branch for any .yaml in  src/split including subdirectories
    branches:
      - develop
    paths:
      - src/split/**/*.yaml

jobs:

  rebundle:
    runs-on: ubuntu-latest
    name: OAS bundler
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CLI bundle #not to be confused with bundle docs to generate html
        run: npx @redocly/openapi-cli bundle src/split/openapi.yaml --output src/openapi.yaml
      - name: commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'rebundle src/split to src/openapi.yaml '
          add: 'src/openapi.yaml'
