name: split OAS

on:
  workflow_dispatch: #manual trigger or ...
  push: #when changes are pushed to default branch for the file src/openAPI.yml
    branches:
      - develop
    paths:
      - "src/openAPI.yml"
jobs:

  split:
    runs-on: ubuntu-latest
    name: Redoc Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CLI split
        run: npx @redocly/openapi-cli split src/openapi.yaml --outDir='src/split'
